### PR TITLE
Fix I1286: URI of NS1 does not match configured value

### LINKED ISSUE #1286: URI of NS1 does not match configured value
The sample-server tries to set the namespace URI to "urn:UmatiSampleServer" 
https://github.com/umati/Sample-Server/blob/84928ab3bc853491c8a483be660384b5b33fb42f/SampleServer.cpp#L123
However, this is not correctly applied. 
image.
An instance of the sample-server is running on opc.tcp://opcua.umati.app:4840.
Can probably be fixed by using the standard setup sequence: https://www.open62541.org/doc/0.3/tutorial_server_firststeps.html

### PR DESCRIPTION
**Pull request by Nico-Brandt**
Fix #1286

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@Nico-Brandt  please sign the CLA.

**Review by ccvca — APPROVED** [review]
Code looks as expected. No functional check.

**Review by GoetzGoerisch — CHANGES_REQUESTED** [review]
Thanks for your contribution.

- Reworded the commit

TODO

- [x] Sign CLA - Nico
- [x] Add copyright into touched files - Nico

**Comment by GoetzGoerisch** [comment]
Thank you for this contribution!

**Pull request merged**
