### PR TITLE
improve/add elements for umati.app woodworking showcase

### PR DESCRIPTION
**Pull request by ChristophRuckstetter**
use ProfilingMachine as deviceClass
toggle RecipeInRun dependin on the machine state
add maxFeedSpeed to ManufacturerSpecific
improve model and url values in identification

fixes https://github.com/umati/Woodworking/issues/9

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
Could you please look into the [error ](https://github.com/umati/Sample-Server/runs/3182606515?check_suite_focus=true#step:4:1339 )of the windows build?

**Comment by ChristophRuckstetter** [comment]
the removing of maxFeedSpeed also fixed the windows build.

**Comment by GoetzGoerisch** [comment]
@ChristophRuckstetter how about: https://github.com/umati/Woodworking/issues/8

**Comment by ChristophRuckstetter** [comment]
@GoetzGoerisch i will look into it. i don't have a fix for it yet.

**Pull request merged**
